---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-on-minikube
  name: nginx-on-minikube
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-on-minikube
  template:
    metadata:
      labels:
        app: nginx-on-minikube
    spec:
      containers:
        - name: nginx
          image: "docker.io/nginx:1.23"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "6Mi"
              cpu: "15m"
            requests:
              memory: "6Mi"
              cpu: "15m"
