apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-on-minikube
  labels:
    app: nginx-on-minikube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-on-minikube
  template:
    metadata:
      labels:
        app: nginx-on-minikube
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.23
        ports:
        - containerPort: 80