--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: nginx-on-minikube
  name: nginx-on-minikube
spec: 
  ports: 
    - 
      nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: nginx-on-minikube
  type: NodePort
